Allow for PHP 7
zicht/messages-bundle pull request #17
Opened 2017-12-22 13:17 UTC by erik-zicht

2018-01-12 11:02 UTC, pbergman requested changes
i prefer to move to new branch and drop BC (also in composer files)

2018-01-15 09:16 UTC, boudewijn-zicht submitted a review, later dismissed

2018-01-16 11:32 UTC, erik-zicht commented
Updated the PR

2018-01-18 14:42 UTC, pbergman approved these changes

2018-01-22 09:11 UTC, merged